### PR TITLE
optimize:Add a list of questions and anchor points for faq.md

### PR DESCRIPTION
**Pull request by lightClouds917**
optimize:
1.Add a list of questions and anchor points for faq.md.
2.Add a new qa.

After optimization, readers can quickly locate the QA.

### CODE REVIEW

**Comment by lovepoem** [comment]
Would you please add the index of QA in english version ?   

docs/en-us/overview/faq.md

**Comment by lightClouds917** [comment]
> Would you please add the index of QA in english version ?
> 
> docs/en-us/overview/faq.md

Ok, I'll add it later today

**Comment by lightClouds917** [comment]
> Would you please add the index of QA in english version ?
> 
> docs/en-us/overview/faq.md

done

**Comment by lovepoem** [comment]
Good job

**Pull request merged**
