### PR TITLE
feature: add new version of Saga designer

### LINKED ISSUE #781: Add a new version Saga designer to the official website
As the title states, add the designer as a demo

### PR DESCRIPTION
**Pull request by ptyin**
## What is the purpose of the change

Add Saga designer to the site. Fixes #781 

## Brief changelog

Move built designer artifacts to `static` directory, and insert a hyperlink in the "user/mode/saga" doc.

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-seata-website/issues) filed for the change(usually before you start working on it).  Trivial changes such as typos do not necessitate a GITHUB issue. Your pull request should solely focus on addressing this specific issue without incorporating any other modifications. Each PR should resolve a single issue.
- [x] Format the pull request title like `doc: add an operations guide document`. Each commit within the pull request should contain a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Test your code locally by running `npm run build`, and make sure it works as expected.
- [x] Ensure that no files under the `build` folder are included in the commit, as well as the `package-lock.json` and `yarn.lock` files.

### CODE REVIEW

**Comment by ptyin** [comment]
| zh-cn | en |
|--------|--------|
| image | image |

**Review by slievrly — APPROVED** [review]
LGTM

**Comment by ptyin** [comment]
@slievrly Accidentally added an unused file, leads to ci failed. Fix it in 26c0399

**Comment by slievrly** [comment]
> @slievrly Accidentally added an unused file, leads to ci failed. Fix it in [26c0399](https://github.com/apache/incubator-seata-website/commit/26c03997d7a1e72c92a0bad092f73b8d7eac9621)

ok.

**Pull request merged**
