### PR TITLE
update saga docs with new features related to v1.4.2

### PR DESCRIPTION
**Pull request by anselleeyy**
add some new feature of saga 1.4.2, which is linked with: [feature: saga support loop execution on state](https://github.com/seata/seata/pull/3468) and [feature: Saga support customize whether update last retry log](https://github.com/seata/seata/pull/3372)

### CODE REVIEW

**Comment by anselleeyy** [comment]
@long187 有空帮忙 review 下哈~

**Comment by a364176773** [comment]
@wangliang181230 @long187 PTAL

**Review by long187 — APPROVED** [review]
LGTM

**Review by wangliang181230 — APPROVED** [review]
LGTM

**Review by a364176773 — APPROVED** [review]
LGTM

**Pull request merged**
