### PR TITLE
doc: optimize 2.0.0 relate notes

### PR DESCRIPTION
**Pull request by wt-better**
## What is the purpose of the change

add 2.0.0 relateNotes

## Brief changelog

add 2.0.0 relateNotes

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/seata/seata.github.io/issues) filed for the change(usually before you start working on it).  Trivial changes such as typos do not necessitate a GITHUB issue. Your pull request should solely focus on addressing this specific issue without incorporating any other modifications. Each PR should resolve a single issue.
- [x] Format the pull request title like `doc: add an operations guide document`. Each commit within the pull request should contain a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Test your code locally by running `npm run build`, and make sure it works as expected.
- [x] Ensure that no files under the `build` folder are included in the commit, as well as the `package-lock.json` and `yarn.lock` files.

### CODE REVIEW

**Review by slievrly — COMMENTED** [review]
The current documentation version also includes the 2.0.0 release notes, so that will have to be changed as well.

**Comment by wt-better** [comment]
> The current documentation version also includes the 2.0.0 release notes, so that will have to be changed as well.

Received, I wiil update it soon

**Comment by wt-better** [comment]
@slievrly  Please check again, thanks.

**Review by slievrly — APPROVED** [review]
LGTM

**Pull request merged**
